spring:
  kafka:
    template:
      default-topic: kafka-tx-topic
      groupId: kafka-tx-group
    producer:
      client-id: KafkaTxProducer
      transactionId-preffix: transaction.prefix.
    consumer:
      properties:
        isolation.level: read_committed
    bootstrap-servers: http://localhost:9092

logging:
  level:
    root: INFO
